config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'users/bookings', to: "bookings#index"
  get 'dashboard', to: "users#index"
  get 'dashboard/bookings', to: "bookings#index"
  get '/api/get/userbookings', to: "bookings#userbookings"
  get '/api/get/waitingbookings', to: "bookings#waitingbookings"
  get '/api/get/singer/:id', to: "singers#getsinger"

  resources :users

  resources :singers do
    resources :ratings
    resources :bookings, only: [ :new, :create, :update, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :singer
  belongs_to :user
  validates :date, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :singer
end

app/models/singer.rb
class Singer < ApplicationRecord
  belongs_to :user
  has_many :ratings
  validates :name, presence: true
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :load_booking, except: %i[index new create userbookings waitingbookings]

  def index
    @bookings = Booking.where(booked: false)
  end

  def create
    already_booked = false
    @bookings_booked = Booking.where(date: params[:booking][:date])
    if @bookings_booked.empty?
      @booking = Booking.new(booking_params)
      @booking.booked = false
      if @booking.save
        redirect_to "/dashboard"
      else
        redirect_to "/singers/"
      end
    else # if the array is not empty it means that someone booked some artist on the same day
      @bookings_booked.each do |booking|
        @booking = Booking.new(booking_params)
        already_booked = true if @booking.singer.name == booking.singer.name
      end
      unless already_booked
        @booking.booked = false
        if @booking.save
          redirect_to "/dashboard"
        else
          redirect_to "/singers/"
        end
      end
    end
  end

  def update
    @singer = Singer.find(params[:singer_id])
    @booking = Booking.find(params[:id])
    if current_user.id == @singer.user_id
      @booking.update(booked: true)
      @singer.save
    end
  end

  def destroy
    @singer = Singer.find(params[:singer_id])
    @booking = Booking.find(params[:id])
    if current_user.id == @singer.user_id
      @booking.delete
      @singer.save
    end
  end

  def show
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
    @singer = Singer.find(params[:singer_id])
  end

  def edit
    @booking.destroy
    redirect_to(bookings_path)
  end

  # custom api method routes

  def userbookings
    @bookings = Booking.where(user_id: current_user.id, booked: true)
    render json: @bookings
  end

  def waitingbookings
    @bookings = Booking.where(user_id: current_user.id, booked: false)
    render json: @bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :singer_id, :date)
  end

  def load_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @singers = Singer.all
  end

  def dashboard
    @singer = Singer.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = Rating.all
  end

  def create
    @rating = Rating.new(rating_params)
    @singer = Singer.find(params[:singer_id])
    @rating.singer = @singer
    @rating.save
    redirect_to singer_path(@singer)
  end

  def new
    @singer = Singer.find(params[:singer_id])
    @rating = Rating.new
  end


  private

  def rating_params
    params.require(:rating).permit(:rating, :review)
  end
end

app/controllers/singers_controller.rb
class SingersController < ApplicationController
  #skip_before_action :authenticate_user!, only: :index
  before_action :set_singer, only: [:show, :edit, :destroy]
  def index
    @singers = Singer.all
    @bookings = Booking.all
  end

  def create
    @singer = Singer.new(singer_params)
    @user = current_user
    @singer.user = @user

    if @singer.save
      redirect_to dashboard_path(@user)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @singer = Singer.find(params[:id])
    @rating = Rating.new
    @ratings = @singer.rating_ids
    @ratingsArray = []
    @ratings.each do |rating|
      @ratingsArray << Rating.find_by(id: rating)
    end
    return @ratingsArray
  end

  def new
    @singer = Singer.new
  end

  def edit
    singer = Singer.find(params[:id])
    if singer.destroy
      redirect_back(fallback_location: root_path)
    else
      error = { detail: "Artist with id #{params[:id]} cannot be deleted" }
    end
  end

  def destroy
    @singer = Singer.find(params[:id])
    @singer.destroy
    redirect_to dashboard_path(@user)
  end

  def getsinger
    singer = Singer.find(params[:id])
    render json: {
      id: singer.id,
      name: singer.name,
      category: singer.category,
      price: singer.price,
      user_id: singer.user_id,
      death_year: singer.death_year,
      bio: singer.bio,
      key: singer.photo.key
    }
  end

  private

  def singer_params
    params.require(:singer).permit(:name, :photo, :price, :category, :bio, :date, :death_year)
  end

  def set_singer
    @singer = Singer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]

  def index
    @user = current_user
    @bookings = Booking.where(user_id: @user.id)
    @bookings_waiting = Booking.where(booked: false)
    @singers = Singer.where(user_id: @user.id)
  end

  def show
    @user = User.find(params[:id])
    raise
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :image_url, :photo, :price, :bio, :death_year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container booking-new">
<h2 class="singer-name-booking">Booking <%= @singer.name %></h2>
  <div class="booking-singer-image">
    <% if @singer.photo.attached? %>
      <%= cl_image_tag @singer.photo.key, class: "booking-img-singer", height: 200, width: 300, crop: :fill %>
      <% else %>
       <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url(https://genesisblockhk.com/wp-content/uploads/2021/12/15-dec-2021-04-2048x1152.jpg)">
    <% end %>
  </div>
  <div class="singer-details">
    <h3><%= @singer.name %>'s Owner: <%= @singer.user.first_name %> <%= @singer.user.last_name %></h3>
    <br>
    <h3>Price: <%= @singer.price %>$</h3>
  </div>

  <div class="form-booking">
    <%= simple_form_for [@singer, @booking] do |b| %>

    <%= b.input :user_id, input_html: { value: current_user.id }, as: :hidden %>
    <%= b.input :singer_id, input_html: { value: @singer.id} , as: :hidden %>
    <%= b.input :date, as: :date, html5: true %>

    <%= b.button :submit, class: "btn btn-primary align-text-bottom btn-booking"%>

    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeadSingerz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>



  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
<video playsinline autoplay muted loop>
     <source src="https://res.cloudinary.com/ddkm6bg5l/video/upload/v1648813373/DeadSingerz/RPReplay_Final1648812974_g284hj.mp4" type="video/mp4">
    Your browser does not support the video tag. I suggest you upgrade your browser.
</video>
      <div class="banner-container">
        <div class="titre-logo">
          <h1>Dead&nbsp;&nbsp;Singerz</h1>
        </div>
        <div class="text-logo">
          <p>Book your DeadSingerz at home for a spectacular showcase</p>
          <div class="d-flex text-logo">
            <p data-controller="animated-number" data-animated-number-start-value="0" data-animated-number-end-value="<%= @singers.length%>" data-animated-number-duration-value="3000">0</p>
            <p style="margin-left: 10px;"> singers already on the platform! </p>
          </div>
        </div>
      </div>
    </div>


<div class="my-container-home text-center">
    <div class="our-deadsingerz text-align-center">
      <div class="wrapper">
        <h2>Our DeadSingerz experiences</h2>
        <p>Choose your Deadsingerz to have your own private showcase at home!</p>
      </div>
        <h3>
            How it works ?
        </h3>
      </div>

      <ul class="program-list multi-format">
          <li class="program-item">
            <div class="batch-details">
              <div class="batch-format">
                <p>
                    Choose your DeadSingerz
                </p>
              </div>
                  <div class="batch-date">
                    You can choose in our catologue of dead stars
                  </div>
            </div>
          </li>

          <li class="program-item">
            <div class="batch-details">
              <div class="batch-format">
                <p>
                    Once the booking done, you will receive your DeadSingerz at home.
                </p>
              </div>
                  <span class="batch-date">
                    Book for one day or more.
                  </span>
            </div>
          </li>
      </ul>
      <div class="half">
          <h2>Experience our DeadSingerz</h2>
        <p>With DeadSingerz you will enjoy your private showcase</p>
      </div>
      <div class="img-michael">
          <img width="640" height="360" class="lozad experience-picture" style="border-radius: 12px;"src="https://res.cloudinary.com/ddkm6bg5l/image/upload/v1648818796/DeadSingerz/micheal-hologram_fsgeql.png">
      </div>
</div>
    </div>

app/views/shared/_booking.html.erb
<div class="min-height-container">
    <h1>My Booking</h2>
    <div class="singers-container container" style="padding-bottom: 20px" data-dashboard-target="userbooking">
      <% if @bookings.empty? %>
        <h3>No singer booked for now.<h3>
      <% else %>
        <% @bookings.each do |booking| %>
          <% if booking.booked == true %>
            <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= cl_image_path booking.singer.photo.key %>')">
              <div class="column">
                <div class="card-body">
                  <h5 class="card-title"><%= booking.singer.name %></h5>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="separator"></div>

    <h2>Waiting bookings</h2>
    <div class="singers-container container" style="padding-bottom: 20px" data-dashboard-target="waitingbooking">
      <% if @bookings.empty? %>
        <h3>No waiting singer for now.<h3>
      <% else %>
        <% @bookings.each do |booking| %>
          <% if booking.booked == false%>
            <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= cl_image_path booking.singer.photo.key %>')">
              <div class="column">
                <div class="card-body">
                  <h5 class="card-title"><%= booking.singer.name %></h5>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="separator"></div>

    <h2>Accept bookings</h2>
    <div class="singers-container container" style="padding-bottom: 20px" data-dashboard-target="acceptbooking">
      <% if @bookings_waiting.empty? %>
        <h3>No waiting singer for now.<h3>
      <% else %>
        <% @bookings_waiting.each do |booking| %>
          <% if booking.booked == false && booking.singer.user_id == current_user.id%>
            <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= cl_image_path booking.singer.photo.key %>')">
              <div class="column">
                <div class="card-body">
                  <h5 class="card-title"><%= booking.singer.name %></h5>
                  <%= link_to "Accept", "/singers/#{booking.singer.id}/bookings/#{booking.id}", :method => :put, data: {action: "click->dashboard#accept", target: "dashboard.accept"},class: "btn btn-success" %>
                  <%= link_to "Decline", "/singers/#{booking.singer.id}/bookings/#{booking.id}",:method => :delete, data: {action: "click->dashboard#decline", target: "dashboard.decline"}, class: "btn btn-danger" %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/shared/_dashboard.html.erb
<div class="min-height-container">
  <h1>Dashboard</h1>

  <%= @user.first_name.capitalize %>
  <%= @user.last_name.capitalize %>

  <div class="separator"></div>

  <h2>Reviews</h2>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="links">
  <li>© 2022 Dead Singerz, Inc.</li>
  <li>Privacy</li>
  <li>Terms</li>
  <li>Sitemap</li>
  <li>Company details</li>
  <li>Choose a language</li>
  <li>French (FR)</li>
  </ul>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag("logo.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", "/dashboard/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dead Singers", "/singers/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add your deadsinger", new_singer_path , class: "nav-link"%>
          </li>
        <% else %>
          <%= link_to "Sign-In", "/users/sign_in", class: "dropdown-item" %>
          <%= link_to "Sign-Up", "/users/sign_up", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_singer.html.erb
<div class="min-height-container">
    <h1>My Singers</h1>
    <% if @singers.empty?  %>
      <h3>No singer for now.</h3>
    <% end %>
    <div class="singers-container container">
      <% @singers.each do |singer|%>
        <% if singer.photo.attached? %>
          <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= cl_image_path singer.photo.key %>')">
        <%else%>
          <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url(https://genesisblockhk.com/wp-content/uploads/2021/12/15-dec-2021-04-2048x1152.jpg)">
        <% end %>
          <div class="column">
            <div class="card-body">
              <h5 class="card-title"><%= singer.name %></h5>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/singers/index.html.erb
<div class="container">
    <% @singers.each do |singer| %>
        <% if singer.photo.attached? %>
          <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('<%= cl_image_path(singer.photo.key) %>')">
        <% else  %>
          <div class="card card-background text-center" style="width: 22rem; background-image: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url(https://genesisblockhk.com/wp-content/uploads/2021/12/15-dec-2021-04-2048x1152.jpg)">
        <% end %>
          <div class="column">
              <div class="index-card-body">
                  <h5 class="card-title"><%= singer.name %></h5>
                  <p class="card-text"></p>
                  <div class="button-container">
                    <%= link_to "Book me!", "/singers/#{singer.id}", class: "btn btn-primary align-text-bottom" %>
                  </div>
              </div>
            </div>
        </div>
    <% end  %>
</div>

app/views/singers/new.html.erb
<div class="new-form">
  <p><%= simple_form_for(@singer) do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :category %>
    <%= f.input :bio %>
    <%= f.input :death_year %>
    <p class="p-photo-field">Add a picture</p>
    <%= f.file_field :photo %>
    <%= f.submit "Add your DeadSingerz", class: "btn btn-primary"%>
  <% end %></p>
</div>

app/views/singers/show.html.erb
<div class="card-image">
  <%= cl_image_tag @singer.photo.key, crop: :fill, class: "img-fluid rounded-start" %>
</div>

<div class="my-container">
      <div class="card-body">
        <h1 class="card-title"><strong><%= @singer.name %></strong></h1>
        <p class="card-text"><small class="text-muted"><% @singer.birth_year %><%= " " %><i class="fa-solid fa-cross"></i><%= @singer.death_year %></small></p>
        <p class="card-text"><small class="text-muted"><%= @singer.category.capitalize %></small></p>
        <p class="card-text"><%= @singer.bio %></p>
        <p class="card-text"><small class="text-muted">Last rented 3 hours ago</small></p>

             <div class="form-booking">
         <%= simple_form_for [@singer, @booking] do |b| %>

         <%= b.input :user_id, input_html: { value: current_user.id }, as: :hidden %>
         <%= b.input :singer_id, input_html: { value: @singer.id} , as: :hidden %>
         <%= b.input :date, as: :date, html5: true %>

         <%= b.button :submit, class: "btn btn-flat"%>

         <%end%>
        </div>
        <br>
        <br>
        <p><%= @singer.name %>'s ratings: </p>
        <% @ratingsArray.each do |rating| %>
                <% case rating.rating %>
                  <% when 1 %>
                  <i class="fa-solid fa-star"></i>
                  <% when 2 %>
                   <i class="fa-solid fa-star"></i> <i class="fa-solid fa-star"></i>
                  <% when 3 %>
                  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
                  <% when 4 %>
                  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
                  <% when 5 %>
                  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i>
                <% end %>

          <p>"<%= "#{rating.review}" %>"</p>
          </p>
          <% end %>

        <div class="my-container container-review">
      <div class=" adding-review">
      <h2>Add a Review to <%= @singer.name %></h2>
        <%= simple_form_for [@singer, @rating] do |f| %>
         <%= f.input :rating %>
         <%= f.input :review %>
         <%= f.submit class: "btn btn-primary align-text-bottom" %>
         <% end %>
      </div>
  </div>





      </div>
    </div>

</div>

app/views/users/index.html.erb
<div class="text-center dashboard-container" data-controller="dashboard">

  <div class="my_container">
    <div class="row">
      <div>
        <ul class="option-navbar">
          <li class="nav-item active">
            <%= link_to "Dashboard", "#dashboard", class: "nav-link link_active", data: {action: "click->dashboard#dashboard", target: "dashboard.dashboardLink"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Singers", "#singers", class: "nav-link", data: {action: "click->dashboard#singers", target: "dashboard.singerLink"} %>
          </li>
          <li class="nav-item">
            <%= link_to "Booking", "#bookings", class: "nav-link", data: {action: "click->dashboard#bookings", target: "dashboard.bookingLink"} %>
          </li>
        </ul>
      </div>
      <div class="separator"></div>
      <div style="min-height: 22em;">
        <div data-dashboard-target="dashboard" class="dashboard active">
          <%= render 'shared/dashboard' %>
        </div>

        <div data-dashboard-target="singer" class="singer not-active">
          <%= render 'shared/singer' %>
        </div>

        <div data-dashboard-target="booking" class="booking not-active">
          <%= render 'shared/booking' %>
        </div>
      </div>
    </div>
  </div>
  <div class="notification-container not-active" data-dashboard-target="notification">
    <div
    data-controller="notification"
    data-notification-delay-value="3000"
    class="good done">

      <p>💀 Successfully accepted booking!</p>

      <!-- <button data-action="notification#hide">Close</button> !-->
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1> <%= @user.first_name %></h1>